"""Create initial tables

Revision ID: 281a93177d8a
Revises: 
Create Date: 2025-08-26 23:28:13.646327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '281a93177d8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('Event', 'Chore', 'Reminder', name='calendarentrytype'), nullable=False),
    sa.Column('recurrences', sa.JSON(), nullable=True),
    sa.Column('none_after', sa.DateTime(), nullable=True),
    sa.Column('none_before', sa.DateTime(), nullable=True),
    sa.Column('responsible', sa.JSON(), nullable=True),
    sa.Column('managers', sa.JSON(), nullable=True),
    sa.Column('previous_entry', sa.Integer(), nullable=True),
    sa.Column('next_entry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_entry'], ['calendarentry.id'], ),
    sa.ForeignKeyConstraint(['previous_entry'], ['calendarentry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chorecompletion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_index', sa.Integer(), nullable=False),
    sa.Column('instance_index', sa.Integer(), nullable=False),
    sa.Column('completed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['calendarentry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chorecompletion_entry_id'), 'chorecompletion', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chorecompletion_entry_id'), table_name='chorecompletion')
    op.drop_table('chorecompletion')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('calendarentry')
    # ### end Alembic commands ###
