name: Run tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.13'
      - name: Run tests
        run: make test
